version: "3.7"
services:
  database:
    image: postgres
    restart: always
    networks:
      - beers
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - beers
volumes:
  db:
    driver: local

networks:
  beers:
    driver: bridge
