// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/castillofranciscodaniel/golang-beers/app"
	"github.com/castillofranciscodaniel/golang-beers/domain"
	provider2 "github.com/castillofranciscodaniel/golang-beers/infrastructure/provider"
)

// Injectors from wire.go:

func InitializeServer() app.ContainerServiceImp {
	healthHandler := app.NewHealthHandler()
	dbManagerPostgres := provider2.NewDbManagerImpl()
	beerRepositoryDb := domain.NewBeersRepositoryDb(dbManagerPostgres)
	currencyClientDefault := provider2.NewCurrencyClientDefault()
	beerService := domain.NewBeersServiceDefault(beerRepositoryDb, currencyClientDefault)
	beerHandler := app.NewBeersHandler(beerService)
	containerServiceImp := app.NewContainerServiceImp(healthHandler, beerHandler)
	return containerServiceImp
}
