// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/castillofranciscodaniel/golang-beers/config"
	domain2 "github.com/castillofranciscodaniel/golang-beers/pkg/domain"
)

// Injectors from wire.go:

func InitializeServer() ContainerServiceImp {
	healthHandler := NewHealthHandler()
	dbManagerPostgres := config.NewDbManagerImpl()
	beerRepositoryDb := domain2.NewBeersRepositoryDb(dbManagerPostgres)
	beerService := domain2.NewBeersServiceImpl(beerRepositoryDb)
	beerHandler := NewBeersHandler(beerService)
	containerServiceImp := NewContainerServiceImp(healthHandler, beerHandler)
	return containerServiceImp
}
